import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/app/auth/Nav'
import QueryWrapper from './auth/QuerryWrapper'
import { Toaster } from 'react-hot-toast'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Post It',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96 ${inter.variable} ${inter.className}`}>
        <QueryWrapper>
          <Nav />
          <Toaster />
          {children}
        </QueryWrapper>
      </body>
    </html>
  )
}
